/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as BillingDebtRouteImport } from './routes/billing/debt'
import { Route as BillingInvoiceRouteImport } from './routes/billing/invoice'
import { Route as DeliveryHistoryRouteImport } from './routes/delivery/history'
import { Route as DeliveryNewRouteImport } from './routes/delivery/new'
import { Route as MasterCatalogRouteImport } from './routes/master/catalog'
import { Route as MasterProjectsRouteImport } from './routes/master/projects'
import { Route as PoIndexRouteImport } from './routes/po/index'
import { Route as PoNewRouteImport } from './routes/po/new'
import { Route as ReportsCostRouteImport } from './routes/reports/cost'
import { Route as ReportsExportRouteImport } from './routes/reports/export'
import { Route as PoIdIndexRouteImport } from './routes/po/$id/index'
import { Route as PoIdEditRouteImport } from './routes/po/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingDebtRoute = BillingDebtRouteImport.update({
  id: '/billing/debt',
  path: '/billing/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoiceRoute = BillingInvoiceRouteImport.update({
  id: '/billing/invoice',
  path: '/billing/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryHistoryRoute = DeliveryHistoryRouteImport.update({
  id: '/delivery/history',
  path: '/delivery/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNewRoute = DeliveryNewRouteImport.update({
  id: '/delivery/new',
  path: '/delivery/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCatalogRoute = MasterCatalogRouteImport.update({
  id: '/master/catalog',
  path: '/master/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProjectsRoute = MasterProjectsRouteImport.update({
  id: '/master/projects',
  path: '/master/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIndexRoute = PoIndexRouteImport.update({
  id: '/po/',
  path: '/po/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoNewRoute = PoNewRouteImport.update({
  id: '/po/new',
  path: '/po/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCostRoute = ReportsCostRouteImport.update({
  id: '/reports/cost',
  path: '/reports/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExportRoute = ReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIdIndexRoute = PoIdIndexRouteImport.update({
  id: '/po/$id/',
  path: '/po/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIdEditRoute = PoIdEditRouteImport.update({
  id: '/po/$id/edit',
  path: '/po/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/billing/debt': typeof BillingDebtRoute
  '/billing/invoice': typeof BillingInvoiceRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/master/catalog': typeof MasterCatalogRoute
  '/master/projects': typeof MasterProjectsRoute
  '/po/new': typeof PoNewRoute
  '/reports/cost': typeof ReportsCostRoute
  '/reports/export': typeof ReportsExportRoute
  '/po/': typeof PoIndexRoute
  '/po/$id/edit': typeof PoIdEditRoute
  '/po/$id/': typeof PoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/billing/debt': typeof BillingDebtRoute
  '/billing/invoice': typeof BillingInvoiceRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/master/catalog': typeof MasterCatalogRoute
  '/master/projects': typeof MasterProjectsRoute
  '/po/new': typeof PoNewRoute
  '/reports/cost': typeof ReportsCostRoute
  '/reports/export': typeof ReportsExportRoute
  '/po': typeof PoIndexRoute
  '/po/$id/edit': typeof PoIdEditRoute
  '/po/$id': typeof PoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/billing/debt': typeof BillingDebtRoute
  '/billing/invoice': typeof BillingInvoiceRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/master/catalog': typeof MasterCatalogRoute
  '/master/projects': typeof MasterProjectsRoute
  '/po/new': typeof PoNewRoute
  '/reports/cost': typeof ReportsCostRoute
  '/reports/export': typeof ReportsExportRoute
  '/po/': typeof PoIndexRoute
  '/po/$id/edit': typeof PoIdEditRoute
  '/po/$id/': typeof PoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/equipment'
    | '/billing/debt'
    | '/billing/invoice'
    | '/delivery/history'
    | '/delivery/new'
    | '/master/catalog'
    | '/master/projects'
    | '/po/new'
    | '/reports/cost'
    | '/reports/export'
    | '/po/'
    | '/po/$id/edit'
    | '/po/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/equipment'
    | '/billing/debt'
    | '/billing/invoice'
    | '/delivery/history'
    | '/delivery/new'
    | '/master/catalog'
    | '/master/projects'
    | '/po/new'
    | '/reports/cost'
    | '/reports/export'
    | '/po'
    | '/po/$id/edit'
    | '/po/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/equipment'
    | '/billing/debt'
    | '/billing/invoice'
    | '/delivery/history'
    | '/delivery/new'
    | '/master/catalog'
    | '/master/projects'
    | '/po/new'
    | '/reports/cost'
    | '/reports/export'
    | '/po/'
    | '/po/$id/edit'
    | '/po/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EquipmentRoute: typeof EquipmentRoute
  BillingDebtRoute: typeof BillingDebtRoute
  BillingInvoiceRoute: typeof BillingInvoiceRoute
  DeliveryHistoryRoute: typeof DeliveryHistoryRoute
  DeliveryNewRoute: typeof DeliveryNewRoute
  MasterCatalogRoute: typeof MasterCatalogRoute
  MasterProjectsRoute: typeof MasterProjectsRoute
  PoNewRoute: typeof PoNewRoute
  ReportsCostRoute: typeof ReportsCostRoute
  ReportsExportRoute: typeof ReportsExportRoute
  PoIndexRoute: typeof PoIndexRoute
  PoIdEditRoute: typeof PoIdEditRoute
  PoIdIndexRoute: typeof PoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/debt': {
      id: '/billing/debt'
      path: '/billing/debt'
      fullPath: '/billing/debt'
      preLoaderRoute: typeof BillingDebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/invoice': {
      id: '/billing/invoice'
      path: '/billing/invoice'
      fullPath: '/billing/invoice'
      preLoaderRoute: typeof BillingInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/history': {
      id: '/delivery/history'
      path: '/delivery/history'
      fullPath: '/delivery/history'
      preLoaderRoute: typeof DeliveryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/new': {
      id: '/delivery/new'
      path: '/delivery/new'
      fullPath: '/delivery/new'
      preLoaderRoute: typeof DeliveryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/catalog': {
      id: '/master/catalog'
      path: '/master/catalog'
      fullPath: '/master/catalog'
      preLoaderRoute: typeof MasterCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/projects': {
      id: '/master/projects'
      path: '/master/projects'
      fullPath: '/master/projects'
      preLoaderRoute: typeof MasterProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/': {
      id: '/po/'
      path: '/po'
      fullPath: '/po/'
      preLoaderRoute: typeof PoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/new': {
      id: '/po/new'
      path: '/po/new'
      fullPath: '/po/new'
      preLoaderRoute: typeof PoNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/cost': {
      id: '/reports/cost'
      path: '/reports/cost'
      fullPath: '/reports/cost'
      preLoaderRoute: typeof ReportsCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/export': {
      id: '/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof ReportsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$id/': {
      id: '/po/$id/'
      path: '/po/$id'
      fullPath: '/po/$id/'
      preLoaderRoute: typeof PoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$id/edit': {
      id: '/po/$id/edit'
      path: '/po/$id/edit'
      fullPath: '/po/$id/edit'
      preLoaderRoute: typeof PoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EquipmentRoute: EquipmentRoute,
  BillingDebtRoute: BillingDebtRoute,
  BillingInvoiceRoute: BillingInvoiceRoute,
  DeliveryHistoryRoute: DeliveryHistoryRoute,
  DeliveryNewRoute: DeliveryNewRoute,
  MasterCatalogRoute: MasterCatalogRoute,
  MasterProjectsRoute: MasterProjectsRoute,
  PoNewRoute: PoNewRoute,
  ReportsCostRoute: ReportsCostRoute,
  ReportsExportRoute: ReportsExportRoute,
  PoIndexRoute: PoIndexRoute,
  PoIdEditRoute: PoIdEditRoute,
  PoIdIndexRoute: PoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
